'use client';

import { useState } from 'react';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { useCreateUser } from '@/hooks/useAuth';
import type { AdminCreateUserResponse } from '@/types/auth.types';

interface RegisterUserModalProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
}

/**
 * Admin modal to create a new user.
 * No password fields — a one-time password is auto-generated by the API
 * and displayed here so the admin can copy and share it with the user.
 */
export function RegisterUserModal({ open, onOpenChange }: RegisterUserModalProps) {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [role, setRole] = useState<'user' | 'admin'>('user');
    const [createdUser, setCreatedUser] = useState<AdminCreateUserResponse | null>(null);
    const [copied, setCopied] = useState(false);

    const createUserMutation = useCreateUser();

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        createUserMutation.mutate(
            { name, email, role: [role] },
            {
                onSuccess: (data) => {
                    setCreatedUser(data);
                },
            }
        );
    };

    const handleCopyOtp = async () => {
        if (!createdUser?.tempPassword) return;
        await navigator.clipboard.writeText(createdUser.tempPassword);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleClose = () => {
        setName('');
        setEmail('');
        setRole('user');
        setCreatedUser(null);
        setCopied(false);
        createUserMutation.reset();
        onOpenChange(false);
    };

    return (
        <Dialog open={open} onOpenChange={handleClose}>
            <DialogContent className="sm:max-w-md">
                {!createdUser ? (
                    <>
                        <DialogHeader>
                            <DialogTitle>Register New User</DialogTitle>
                            <DialogDescription>
                                Create a user account. A one-time password will be generated
                                for you to share with the user.
                            </DialogDescription>
                        </DialogHeader>

                        <form onSubmit={handleSubmit} className="space-y-4 mt-2">
                            <div className="space-y-2">
                                <Label htmlFor="reg-name">Full Name</Label>
                                <Input
                                    id="reg-name"
                                    type="text"
                                    placeholder="Enter full name"
                                    value={name}
                                    onChange={(e) => setName(e.target.value)}
                                    required
                                    disabled={createUserMutation.isPending}
                                />
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="reg-email">Email</Label>
                                <Input
                                    id="reg-email"
                                    type="email"
                                    placeholder="Enter email address"
                                    value={email}
                                    onChange={(e) => setEmail(e.target.value)}
                                    required
                                    disabled={createUserMutation.isPending}
                                />
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="reg-role">Role</Label>
                                <Select
                                    value={role}
                                    onValueChange={(v) => setRole(v as 'user' | 'admin')}
                                    disabled={createUserMutation.isPending}
                                >
                                    <SelectTrigger id="reg-role">
                                        <SelectValue placeholder="Select role" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="user">User</SelectItem>
                                        <SelectItem value="admin">Admin</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>

                            {createUserMutation.isError && (
                                <div className="bg-destructive/10 text-destructive p-3 rounded-md text-sm border border-destructive/20">
                                    {(createUserMutation.error as Error)?.message ?? 'Failed to create user'}
                                </div>
                            )}

                            <div className="flex gap-2 justify-end pt-2">
                                <Button
                                    type="button"
                                    variant="outline"
                                    onClick={handleClose}
                                    disabled={createUserMutation.isPending}
                                >
                                    Cancel
                                </Button>
                                <Button
                                    type="submit"
                                    disabled={createUserMutation.isPending}
                                >
                                    {createUserMutation.isPending ? 'Creating...' : 'Create User'}
                                </Button>
                            </div>
                        </form>
                    </>
                ) : (
                    <>
                        <DialogHeader>
                            <DialogTitle>User Created Successfully</DialogTitle>
                            <DialogDescription>
                                Share the one-time password below with{' '}
                                <strong>{createdUser.email}</strong>. They will be prompted
                                to change it on first login.
                            </DialogDescription>
                        </DialogHeader>

                        <div className="space-y-4 mt-2">
                            <div className="space-y-1">
                                <p className="text-sm text-muted-foreground">Name</p>
                                <p className="font-medium">{createdUser.name}</p>
                            </div>
                            <div className="space-y-1">
                                <p className="text-sm text-muted-foreground">Email</p>
                                <p className="font-medium">{createdUser.email}</p>
                            </div>
                            <div className="space-y-1">
                                <p className="text-sm text-muted-foreground">Role</p>
                                <p className="font-medium capitalize">
                                    {createdUser.role?.join(', ')}
                                </p>
                            </div>

                            <div className="space-y-2">
                                <p className="text-sm font-medium">One-Time Password</p>
                                <div className="flex items-center gap-2">
                                    <code className="flex-1 bg-muted px-3 py-2 rounded-md text-sm font-mono tracking-wider select-all">
                                        {createdUser.tempPassword}
                                    </code>
                                    <Button
                                        type="button"
                                        variant="outline"
                                        size="sm"
                                        onClick={handleCopyOtp}
                                    >
                                        {copied ? 'Copied!' : 'Copy'}
                                    </Button>
                                </div>
                                <p className="text-xs text-muted-foreground">
                                    This password is shown only once. The user&apos;s account will
                                    be activated after they complete the password change.
                                </p>
                            </div>

                            <div className="flex justify-end pt-2">
                                <Button onClick={handleClose}>Done</Button>
                            </div>
                        </div>
                    </>
                )}
            </DialogContent>
        </Dialog>
    );
}
