apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "h2bis-pb.labels" . | nindent 4 }}
type: Opaque
stringData:
  # API service
  api-mongodb-uri: {{ .Values.api.env.MONGODB_URI | quote }}
  jwt-access-secret: {{ .Values.api.env.JWT_ACCESS_SECRET | quote }}
  jwt-refresh-secret: {{ .Values.api.env.JWT_REFRESH_SECRET | quote }}

  # AI service
  openai-api-key: {{ .Values.ai.env.OPENAI_API_KEY | quote }}
