apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "h2bis-pb.labels" . | nindent 4 }}
type: Opaque
stringData:
  # API service
  api-mongodb-uri: {{ .Values.api.env.MONGODB_URI | quote }}
  jwt-access-secret: {{ .Values.api.env.JWT_ACCESS_SECRET | quote }}
  jwt-refresh-secret: {{ .Values.api.env.JWT_REFRESH_SECRET | quote }}
  github-client-id: {{ .Values.api.env.GITHUB_CLIENT_ID | quote }}
  github-client-secret: {{ .Values.api.env.GITHUB_CLIENT_SECRET | quote }}
  github-callback-url: {{ .Values.api.env.GITHUB_CALLBACK_URL | quote }}
  openai-api-key: {{ .Values.api.env.OPENAI_API_KEY | quote }}

  # Web service
  nextauth-secret: {{ .Values.web.env.NEXTAUTH_SECRET | quote }}
